services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: postgres

volumes:
  postgres-data: {}
